package com.sqli.model;

// Generated 15 nov. 2014 14:53:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action", catalog = "gestionformation")
public class Action implements java.io.Serializable {

	private Integer idAction;
	private Profil profil;
	private String droit;
	private int code;

	public Action() {
	}

	public Action(Profil profil, String droit, int code) {
		this.profil = profil;
		this.droit = droit;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_action", unique = true, nullable = false)
	public Integer getIdAction() {
		return this.idAction;
	}

	public void setIdAction(Integer idAction) {
		this.idAction = idAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_profil", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@Column(name = "droit", nullable = false)
	public String getDroit() {
		return this.droit;
	}

	public void setDroit(String droit) {
		this.droit = droit;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

}
