package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Collaborateur generated by hbm2java
 */
@Entity
@Table(name = "collaborateur", catalog = "gestionformation")
public class Collaborateur implements java.io.Serializable {

	private Integer idCollaborateur;
	private String matricule;
	private Date nomCollaborateur;
	private String prenomCollaborateur;
	private String adrCollaborateur;
	private String site;
	private String busnessUnit;
	private String sexe;
	private Date dateEmbauche;
	private String email;
	private String diplome;
	private boolean etatManagerRh;
	private boolean ancienCollaborateur;
	private Set assistes = new HashSet(0);
	private Set evaluations = new HashSet(0);
	private Set comptes = new HashSet(0);

	public Collaborateur() {
	}

	public Collaborateur(String matricule, Date nomCollaborateur,
			String prenomCollaborateur, String adrCollaborateur, String site,
			String busnessUnit, String sexe, Date dateEmbauche, String email,
			String diplome, boolean etatManagerRh, boolean ancienCollaborateur) {
		this.matricule = matricule;
		this.nomCollaborateur = nomCollaborateur;
		this.prenomCollaborateur = prenomCollaborateur;
		this.adrCollaborateur = adrCollaborateur;
		this.site = site;
		this.busnessUnit = busnessUnit;
		this.sexe = sexe;
		this.dateEmbauche = dateEmbauche;
		this.email = email;
		this.diplome = diplome;
		this.etatManagerRh = etatManagerRh;
		this.ancienCollaborateur = ancienCollaborateur;
	}

	public Collaborateur(String matricule, Date nomCollaborateur,
			String prenomCollaborateur, String adrCollaborateur, String site,
			String busnessUnit, String sexe, Date dateEmbauche, String email,
			String diplome, boolean etatManagerRh, boolean ancienCollaborateur,
			Set assistes, Set evaluations, Set comptes) {
		this.matricule = matricule;
		this.nomCollaborateur = nomCollaborateur;
		this.prenomCollaborateur = prenomCollaborateur;
		this.adrCollaborateur = adrCollaborateur;
		this.site = site;
		this.busnessUnit = busnessUnit;
		this.sexe = sexe;
		this.dateEmbauche = dateEmbauche;
		this.email = email;
		this.diplome = diplome;
		this.etatManagerRh = etatManagerRh;
		this.ancienCollaborateur = ancienCollaborateur;
		this.assistes = assistes;
		this.evaluations = evaluations;
		this.comptes = comptes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_collaborateur", unique = true, nullable = false)
	public Integer getIdCollaborateur() {
		return this.idCollaborateur;
	}

	public void setIdCollaborateur(Integer idCollaborateur) {
		this.idCollaborateur = idCollaborateur;
	}

	@Column(name = "matricule", nullable = false, length = 50)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nom_collaborateur", nullable = false, length = 10)
	public Date getNomCollaborateur() {
		return this.nomCollaborateur;
	}

	public void setNomCollaborateur(Date nomCollaborateur) {
		this.nomCollaborateur = nomCollaborateur;
	}

	@Column(name = "prenom_collaborateur", nullable = false)
	public String getPrenomCollaborateur() {
		return this.prenomCollaborateur;
	}

	public void setPrenomCollaborateur(String prenomCollaborateur) {
		this.prenomCollaborateur = prenomCollaborateur;
	}

	@Column(name = "adr_collaborateur", nullable = false)
	public String getAdrCollaborateur() {
		return this.adrCollaborateur;
	}

	public void setAdrCollaborateur(String adrCollaborateur) {
		this.adrCollaborateur = adrCollaborateur;
	}

	@Column(name = "site", nullable = false)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "busness_unit", nullable = false)
	public String getBusnessUnit() {
		return this.busnessUnit;
	}

	public void setBusnessUnit(String busnessUnit) {
		this.busnessUnit = busnessUnit;
	}

	@Column(name = "sexe", nullable = false, length = 30)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_embauche", nullable = false, length = 10)
	public Date getDateEmbauche() {
		return this.dateEmbauche;
	}

	public void setDateEmbauche(Date dateEmbauche) {
		this.dateEmbauche = dateEmbauche;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "diplome", nullable = false)
	public String getDiplome() {
		return this.diplome;
	}

	public void setDiplome(String diplome) {
		this.diplome = diplome;
	}

	@Column(name = "etat_managerRH", nullable = false)
	public boolean isEtatManagerRh() {
		return this.etatManagerRh;
	}

	public void setEtatManagerRh(boolean etatManagerRh) {
		this.etatManagerRh = etatManagerRh;
	}

	@Column(name = "ancien_collaborateur", nullable = false)
	public boolean isAncienCollaborateur() {
		return this.ancienCollaborateur;
	}

	public void setAncienCollaborateur(boolean ancienCollaborateur) {
		this.ancienCollaborateur = ancienCollaborateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collaborateur")
	public Set getAssistes() {
		return this.assistes;
	}

	public void setAssistes(Set assistes) {
		this.assistes = assistes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collaborateur")
	public Set getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set evaluations) {
		this.evaluations = evaluations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collaborateur")
	public Set getComptes() {
		return this.comptes;
	}

	public void setComptes(Set comptes) {
		this.comptes = comptes;
	}

}
