package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", catalog = "gestionformation")
public class Compte implements java.io.Serializable {

	private Integer idCompte;
	private Formateur formateur;
	private Collaborateur collaborateur;
	private String login;
	private String password;
	private boolean etatcompte;
	private Set profils = new HashSet(0);

	public Compte() {
	}

	public Compte(Formateur formateur, Collaborateur collaborateur,
			String login, String password, boolean etatcompte) {
		this.formateur = formateur;
		this.collaborateur = collaborateur;
		this.login = login;
		this.password = password;
		this.etatcompte = etatcompte;
	}

	public Compte(Formateur formateur, Collaborateur collaborateur,
			String login, String password, boolean etatcompte, Set profils) {
		this.formateur = formateur;
		this.collaborateur = collaborateur;
		this.login = login;
		this.password = password;
		this.etatcompte = etatcompte;
		this.profils = profils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_compte", unique = true, nullable = false)
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formateur", nullable = false)
	public Formateur getFormateur() {
		return this.formateur;
	}

	public void setFormateur(Formateur formateur) {
		this.formateur = formateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_collaborateur", nullable = false)
	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "etatcompte", nullable = false)
	public boolean isEtatcompte() {
		return this.etatcompte;
	}

	public void setEtatcompte(boolean etatcompte) {
		this.etatcompte = etatcompte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set getProfils() {
		return this.profils;
	}

	public void setProfils(Set profils) {
		this.profils = profils;
	}

}
