package com.sqli.model;

// Generated 15 nov. 2014 14:53:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Compte generated by hbm2java
 */
@Proxy(lazy=false)
@Entity
@Table(name = "compte", catalog = "gestionformation")
public class Compte implements java.io.Serializable {

	private Integer idCompte;
	private Personnel personnel;
	private Profil profil;
	private String login;
	private String password;
	private boolean etatcompte;

	public Compte() {
	}

	public Compte(Personnel personnel, Profil profil, String login,
			String password, boolean etatcompte) {
		this.personnel = personnel;
		this.profil = profil;
		this.login = login;
		this.password = password;
		this.etatcompte = etatcompte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_compte", unique = true, nullable = false)
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matricule", nullable = false)
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_profil", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "etatcompte", nullable = false)
	public boolean isEtatcompte() {
		return this.etatcompte;
	}

	public void setEtatcompte(boolean etatcompte) {
		this.etatcompte = etatcompte;
	}

}
