package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", catalog = "gestionformation")
public class Document implements java.io.Serializable {

	private Integer idDoc;
	private Session session;
	private String fichierPath;

	public Document() {
	}

	public Document(Session session, String fichierPath) {
		this.session = session;
		this.fichierPath = fichierPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_doc", unique = true, nullable = false)
	public Integer getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(Integer idDoc) {
		this.idDoc = idDoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_session", nullable = false)
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Column(name = "fichier_path", nullable = false, length = 512)
	public String getFichierPath() {
		return this.fichierPath;
	}

	public void setFichierPath(String fichierPath) {
		this.fichierPath = fichierPath;
	}

}
