package com.sqli.model;

// Generated 15 nov. 2014 15:31:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EvaluationChaud generated by hbm2java
 */
@Entity
@Table(name = "evaluation_chaud", catalog = "gestionformation")
public class EvaluationChaud implements java.io.Serializable {

	private Integer idEvaluationChaud;
	private Evaluation evaluation;
	private String commentaire;
	private String suggestion;
	private Date date;
	private int idEvaluation;
	private Set<Reponse> reponses = new HashSet<Reponse>(0);

	public EvaluationChaud() {
	}

	public EvaluationChaud(Evaluation evaluation, String commentaire,
			String suggestion, Date date, int idEvaluation) {
		this.evaluation = evaluation;
		this.commentaire = commentaire;
		this.suggestion = suggestion;
		this.date = date;
		this.idEvaluation = idEvaluation;
	}

	public EvaluationChaud(Evaluation evaluation, String commentaire,
			String suggestion, Date date, int idEvaluation, Set<Reponse> reponses) {
		this.evaluation = evaluation;
		this.commentaire = commentaire;
		this.suggestion = suggestion;
		this.date = date;
		this.idEvaluation = idEvaluation;
		this.reponses = reponses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_evaluation_chaud", unique = true, nullable = false)
	public Integer getIdEvaluationChaud() {
		return this.idEvaluationChaud;
	}

	public void setIdEvaluationChaud(Integer idEvaluationChaud) {
		this.idEvaluationChaud = idEvaluationChaud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_session", nullable = false)
	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	@Column(name = "commentaire", nullable = false, length = 256)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "suggestion", nullable = false, length = 256)
	public String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "id_evaluation", nullable = false)
	public int getIdEvaluation() {
		return this.idEvaluation;
	}

	public void setIdEvaluation(int idEvaluation) {
		this.idEvaluation = idEvaluation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluationChaud")
	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> reponses) {
		this.reponses = reponses;
	}

}
