package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EvaluationFroid generated by hbm2java
 */
@Entity
@Table(name = "evaluation_froid", catalog = "gestionformation")
public class EvaluationFroid implements java.io.Serializable {

	private Integer idEvaluationFroid;
	private Evaluation evaluation;
	private String periode;
	private boolean applicabiliteFormatiom;
	private String raisonApplicabilite;
	private boolean efficaciteCourtterme;
	private String complementFormation;
	private String commentaireCollaborateur;
	private Date date;
	private Set objectifs = new HashSet(0);

	public EvaluationFroid() {
	}

	public EvaluationFroid(Evaluation evaluation, String periode,
			boolean applicabiliteFormatiom, String raisonApplicabilite,
			boolean efficaciteCourtterme, String complementFormation,
			String commentaireCollaborateur, Date date) {
		this.evaluation = evaluation;
		this.periode = periode;
		this.applicabiliteFormatiom = applicabiliteFormatiom;
		this.raisonApplicabilite = raisonApplicabilite;
		this.efficaciteCourtterme = efficaciteCourtterme;
		this.complementFormation = complementFormation;
		this.commentaireCollaborateur = commentaireCollaborateur;
		this.date = date;
	}

	public EvaluationFroid(Evaluation evaluation, String periode,
			boolean applicabiliteFormatiom, String raisonApplicabilite,
			boolean efficaciteCourtterme, String complementFormation,
			String commentaireCollaborateur, Date date, Set objectifs) {
		this.evaluation = evaluation;
		this.periode = periode;
		this.applicabiliteFormatiom = applicabiliteFormatiom;
		this.raisonApplicabilite = raisonApplicabilite;
		this.efficaciteCourtterme = efficaciteCourtterme;
		this.complementFormation = complementFormation;
		this.commentaireCollaborateur = commentaireCollaborateur;
		this.date = date;
		this.objectifs = objectifs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_evaluation_froid", unique = true, nullable = false)
	public Integer getIdEvaluationFroid() {
		return this.idEvaluationFroid;
	}

	public void setIdEvaluationFroid(Integer idEvaluationFroid) {
		this.idEvaluationFroid = idEvaluationFroid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref_evaluation", nullable = false)
	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	@Column(name = "periode", nullable = false)
	public String getPeriode() {
		return this.periode;
	}

	public void setPeriode(String periode) {
		this.periode = periode;
	}

	@Column(name = "applicabilite_formatiom", nullable = false)
	public boolean isApplicabiliteFormatiom() {
		return this.applicabiliteFormatiom;
	}

	public void setApplicabiliteFormatiom(boolean applicabiliteFormatiom) {
		this.applicabiliteFormatiom = applicabiliteFormatiom;
	}

	@Column(name = "raison_applicabilite", nullable = false)
	public String getRaisonApplicabilite() {
		return this.raisonApplicabilite;
	}

	public void setRaisonApplicabilite(String raisonApplicabilite) {
		this.raisonApplicabilite = raisonApplicabilite;
	}

	@Column(name = "efficacite_courtterme", nullable = false)
	public boolean isEfficaciteCourtterme() {
		return this.efficaciteCourtterme;
	}

	public void setEfficaciteCourtterme(boolean efficaciteCourtterme) {
		this.efficaciteCourtterme = efficaciteCourtterme;
	}

	@Column(name = "complement_formation", nullable = false)
	public String getComplementFormation() {
		return this.complementFormation;
	}

	public void setComplementFormation(String complementFormation) {
		this.complementFormation = complementFormation;
	}

	@Column(name = "commentaire_collaborateur", nullable = false)
	public String getCommentaireCollaborateur() {
		return this.commentaireCollaborateur;
	}

	public void setCommentaireCollaborateur(String commentaireCollaborateur) {
		this.commentaireCollaborateur = commentaireCollaborateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluationFroid")
	public Set getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(Set objectifs) {
		this.objectifs = objectifs;
	}

}
