package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formateur generated by hbm2java
 */
@Entity
@Table(name = "formateur", catalog = "gestionformation")
public class Formateur implements java.io.Serializable {

	private Integer idFormateur;
	private String nom;
	private String prenom;
	private String adrFormateur;
	private String site;
	private String diplome;
	private Set comptes = new HashSet(0);
	private Set sessions = new HashSet(0);

	public Formateur() {
	}

	public Formateur(String nom, String prenom, String adrFormateur,
			String diplome) {
		this.nom = nom;
		this.prenom = prenom;
		this.adrFormateur = adrFormateur;
		this.diplome = diplome;
	}

	public Formateur(String nom, String prenom, String adrFormateur,
			String site, String diplome, Set comptes, Set sessions) {
		this.nom = nom;
		this.prenom = prenom;
		this.adrFormateur = adrFormateur;
		this.site = site;
		this.diplome = diplome;
		this.comptes = comptes;
		this.sessions = sessions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_formateur", unique = true, nullable = false)
	public Integer getIdFormateur() {
		return this.idFormateur;
	}

	public void setIdFormateur(Integer idFormateur) {
		this.idFormateur = idFormateur;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adr_formateur", nullable = false, length = 512)
	public String getAdrFormateur() {
		return this.adrFormateur;
	}

	public void setAdrFormateur(String adrFormateur) {
		this.adrFormateur = adrFormateur;
	}

	@Column(name = "site", length = 512)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "diplome", nullable = false)
	public String getDiplome() {
		return this.diplome;
	}

	public void setDiplome(String diplome) {
		this.diplome = diplome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formateur")
	public Set getComptes() {
		return this.comptes;
	}

	public void setComptes(Set comptes) {
		this.comptes = comptes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formateur")
	public Set getSessions() {
		return this.sessions;
	}

	public void setSessions(Set sessions) {
		this.sessions = sessions;
	}

}
