package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", catalog = "gestionformation")
public class Profil implements java.io.Serializable {

	private Integer idProfil;
	private Compte compte;
	private String intituleProfil;
	private Set actions = new HashSet(0);

	public Profil() {
	}

	public Profil(Compte compte, String intituleProfil) {
		this.compte = compte;
		this.intituleProfil = intituleProfil;
	}

	public Profil(Compte compte, String intituleProfil, Set actions) {
		this.compte = compte;
		this.intituleProfil = intituleProfil;
		this.actions = actions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_profil", unique = true, nullable = false)
	public Integer getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(Integer idProfil) {
		this.idProfil = idProfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "intitule_profil", nullable = false)
	public String getIntituleProfil() {
		return this.intituleProfil;
	}

	public void setIntituleProfil(String intituleProfil) {
		this.intituleProfil = intituleProfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set getActions() {
		return this.actions;
	}

	public void setActions(Set actions) {
		this.actions = actions;
	}

}
