package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReponseId generated by hbm2java
 */
@Embeddable
public class ReponseId implements java.io.Serializable {

	private int idEvaluationChaud;
	private int idQuestion;

	public ReponseId() {
	}

	public ReponseId(int idEvaluationChaud, int idQuestion) {
		this.idEvaluationChaud = idEvaluationChaud;
		this.idQuestion = idQuestion;
	}

	@Column(name = "id_evaluation_chaud", nullable = false)
	public int getIdEvaluationChaud() {
		return this.idEvaluationChaud;
	}

	public void setIdEvaluationChaud(int idEvaluationChaud) {
		this.idEvaluationChaud = idEvaluationChaud;
	}

	@Column(name = "id_question", nullable = false)
	public int getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(int idQuestion) {
		this.idQuestion = idQuestion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReponseId))
			return false;
		ReponseId castOther = (ReponseId) other;

		return (this.getIdEvaluationChaud() == castOther.getIdEvaluationChaud())
				&& (this.getIdQuestion() == castOther.getIdQuestion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEvaluationChaud();
		result = 37 * result + this.getIdQuestion();
		return result;
	}

}
