package com.sqli.model;

// Generated 13 nov. 2014 19:47:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "gestionformation")
public class Session implements java.io.Serializable {

	private Integer codeSession;
	private Formation formation;
	private Formateur formateur;
	private Date dateRealis;
	private String intitule;
	private int duree;
	private Date dateButoire;
	private boolean realisee;
	private Set documents = new HashSet(0);
	private Set assistes = new HashSet(0);

	public Session() {
	}

	public Session(Formation formation, Formateur formateur, Date dateRealis,
			String intitule, int duree, Date dateButoire, boolean realisee) {
		this.formation = formation;
		this.formateur = formateur;
		this.dateRealis = dateRealis;
		this.intitule = intitule;
		this.duree = duree;
		this.dateButoire = dateButoire;
		this.realisee = realisee;
	}

	public Session(Formation formation, Formateur formateur, Date dateRealis,
			String intitule, int duree, Date dateButoire, boolean realisee,
			Set documents, Set assistes) {
		this.formation = formation;
		this.formateur = formateur;
		this.dateRealis = dateRealis;
		this.intitule = intitule;
		this.duree = duree;
		this.dateButoire = dateButoire;
		this.realisee = realisee;
		this.documents = documents;
		this.assistes = assistes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "code_session", unique = true, nullable = false)
	public Integer getCodeSession() {
		return this.codeSession;
	}

	public void setCodeSession(Integer codeSession) {
		this.codeSession = codeSession;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formation", nullable = false)
	public Formation getFormation() {
		return this.formation;
	}

	public void setFormation(Formation formation) {
		this.formation = formation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formateur", nullable = false)
	public Formateur getFormateur() {
		return this.formateur;
	}

	public void setFormateur(Formateur formateur) {
		this.formateur = formateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_realis", nullable = false, length = 10)
	public Date getDateRealis() {
		return this.dateRealis;
	}

	public void setDateRealis(Date dateRealis) {
		this.dateRealis = dateRealis;
	}

	@Column(name = "intitule", nullable = false)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@Column(name = "duree", nullable = false)
	public int getDuree() {
		return this.duree;
	}

	public void setDuree(int duree) {
		this.duree = duree;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_butoire", nullable = false, length = 10)
	public Date getDateButoire() {
		return this.dateButoire;
	}

	public void setDateButoire(Date dateButoire) {
		this.dateButoire = dateButoire;
	}

	@Column(name = "realisee", nullable = false)
	public boolean isRealisee() {
		return this.realisee;
	}

	public void setRealisee(boolean realisee) {
		this.realisee = realisee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	public Set getAssistes() {
		return this.assistes;
	}

	public void setAssistes(Set assistes) {
		this.assistes = assistes;
	}

}
