package com.SQLI.WZA.model;

// Generated 2 nov. 2014 19:02:33 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssisteId generated by hbm2java
 */
@Embeddable
public class AssisteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCollaborateur;
	private int idSession;

	public AssisteId() {
	}

	public AssisteId(int idCollaborateur, int idSession) {
		this.idCollaborateur = idCollaborateur;
		this.idSession = idSession;
	}

	@Column(name = "id_collaborateur", nullable = false)
	public int getIdCollaborateur() {
		return this.idCollaborateur;
	}

	public void setIdCollaborateur(int idCollaborateur) {
		this.idCollaborateur = idCollaborateur;
	}

	@Column(name = "id_session", nullable = false)
	public int getIdSession() {
		return this.idSession;
	}

	public void setIdSession(int idSession) {
		this.idSession = idSession;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssisteId))
			return false;
		AssisteId castOther = (AssisteId) other;

		return (this.getIdCollaborateur() == castOther.getIdCollaborateur())
				&& (this.getIdSession() == castOther.getIdSession());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCollaborateur();
		result = 37 * result + this.getIdSession();
		return result;
	}

}
